chains:
    elystestnet-1:
        factory: "elys14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s3fsthx"
        gas_prices: 0.25
        gas_adjustment: 1.3
        threshold: 1000000
        rpc_timeout: 9.0
        include_evented_tasks: true
        custom_sources:
            "Elys Network":
                rpc: http://localhost:26657
